function [fullFilenameCDF, exportSuccessFlag, CDFVariableNames] = ...
        generateSEEDCDF(info, fullFilenameCDF, missionDayOfYear, ...
        SEEDData, DoseData, TempData, time)

%This function is called by combineData.m.  This function will output a
%CDF file. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%  Get the NASA CDF Data    %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Get the master file information.
CDFInfo = spdfcdfinfo(info.CDFMasterFilename);

%Make plots of the raw data.
%plotRawCDFData(info, time, SEEDData, DoseData);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%  Handle the TT2000 data      %%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Generate the TT2000 time intervals and corresponding counts.  The
%TT2000Time variable is valid for both SEED data and Dosimeter data at this
%time.  
[TT2000Time, UTCTime, TT2000SEEDCounts, TT2000DosimeterCounts, ...
    TT2000TempCounts] = generateTT2000(info, time, SEEDData, DoseData, ...
    TempData);

%Convert the Dosimeter counts to dose values.  This function also ensures
%that both counts and dose do not have negative values.  I also use this
%function to set the number of channels to be three.
[DosimeterCounts, DosimeterDose] = getCDFDosimeterCountsAndDose(info, ...
    TT2000DosimeterCounts);

%Next fix some of the SEED data issues.
[SEEDTime, SEEDCounts, uniqueDeltaTime] = ...
    getCDFUniqueDifferencedSEEDData(info, TT2000Time, TT2000SEEDCounts);

%Determine the flux.  This function will return a structure containing the
%actual flux as well as estimates of the error/uncertainty in the flux.
[fluxAll, flux15] = getCDFFlux(info, SEEDTime, SEEDCounts, uniqueDeltaTime);

%Convert the temperature data to actual physical values.
TemperatureData = convertSEEDTemperature(TT2000TempCounts);

%Make plots of the processed data.
%plotProcessedSEEDDoseData(info, DosimeterCounts, TT2000Time, ...
%    fluxAll, flux15, SEEDTime);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%   Set up for generating the CDF file %%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Set up the Dosimeter Counts and Dose labels.
SEEDDosimeterCountsLabel = {'SEED Dosimeter Counts Channel 1', ...
    'SEED Dosimeter Counts Channel 2', 'SEED Dosimeter Counts Channel 3'};

SEEDDosimeterDoseLabel = {'SEED Dosimeter Dose Channel 1', ...
    'SEED Dosimeter Dose Channel 2', 'SEED Dosimeter Dose Channel 3'};

%Set up the dosimeter counts to rads conversion factors.
DosimeterCToF = [info.DosimeterChannel1CountsToRads, ...
    info.DosimeterChannel2CountsToRads, info.DosimeterChannel3CountsToRads];

%Convert the Dosimeter structures into arrays.
DosimeterCountsArray = [DosimeterCounts.channel1, DosimeterCounts.channel2, ...
    DosimeterCounts.channel3];
DosimeterDoseArray = [DosimeterDose.channel1, DosimeterDose.channel2, ...
    DosimeterDose.channel3];

%Set up the cell that contains the CDF variables we want to write to file.
CDFVariableNames = {'Epoch', ...
    'SEED_Time_Dt15_Good', ...
    'SEED_Electron_Counts_Total', ...
    'SEED_Electron_Counts_Dt15_Good', ...
    'SEED_Electron_Flux_Total', ...
    'SEED_Electron_Flux_Dt15_Good', ...
    'SEED_Energy_Channels', ...
    'SEED_Geometric_Factor', ...
    'SEED_Dosimeter_Time', ...
    'SEED_Dosimeter_Counts', ...
    'SEED_Dosimeter_Dose', ...
    'SEED_Dosimeter_Counts_To_Dose', ...
    'SEED_Dosimeter_Channels', ...
    'SEED_Dosimeter_Counts_LABEL', ...
    'SEED_Dosimeter_Dose_Label', ...
    'SEED_Temperature'};

CDFVariables = {CDFVariableNames{1}, SEEDTime.TT2000, ...
    CDFVariableNames{2}, SEEDTime.dt15TT2000, ...
    CDFVariableNames{3}, uint32(SEEDCounts.differencedCounts), ...
    CDFVariableNames{4}, uint32(SEEDCounts.differencedDt15Counts), ...
    CDFVariableNames{5}, single(fluxAll), ...
    CDFVariableNames{6}, single(flux15), ...
    CDFVariableNames{7}, single(info.energyBins(:, 2)), ...
    CDFVariableNames{8}, single(info.g), ...
    CDFVariableNames{9}, TT2000Time, ...
    CDFVariableNames{10}, uint32(DosimeterCountsArray), ...
    CDFVariableNames{11}, single(DosimeterDoseArray), ...
    CDFVariableNames{12}, single(DosimeterCToF), ...
    CDFVariableNames{13}, uint32([1, 2, 3]), ...
    CDFVariableNames{14}, SEEDDosimeterCountsLabel, ...
    CDFVariableNames{15}, SEEDDosimeterDoseLabel, ...
    CDFVariableNames{16}, single(TemperatureData)
    };

%Set up some variables to use for the spdfcdfwrite command.  This code is 
%taken directly from the spdfcdfwrite.m examples comments section(line 430).
for p = 1:length(CDFInfo.Variables(:,1))
    varCompress{(2*p)-1} = CDFInfo.Variables{p, 1}; 	% Variable name
    varCompress{2*p} = CDFInfo.Variables{p, 7};	% Variable compression
    blockingFactor{2*p-1} = CDFInfo.Variables{p, 1};		% Variable name
    blockingFactor{2*p} = CDFInfo.Variables{p, 8};		% Variable blocking factor
    varDataTypes{2*p-1} = CDFInfo.Variables{p, 1};	% Variable name
    varDataTypes{2*p} = CDFInfo.Variables{p, 4};	% Variable data type
    pad{2*p-1} = CDFInfo.Variables{p, 1};		% Variable name
    pad{2*p} = CDFInfo.Variables{p, 9};		% Variable pad value
end

%Set up the record bound variable.  This code is taken directly from the
%spdfcdfwrite.m examples comments section(line 442).
rbvars = {CDFInfo.Variables{:, 1}};		% Variable names for recordbound
for p = length(rbvars) : -1 : 1
    if (strncmpi(CDFInfo.Variables{p, 5}, 'f', 1) == 1)	% NRV variable
        rbvars(:, p) = []; 	  		% Remove it
    end
end

%Now write the file.
spdfcdfwrite(fullFilenameCDF, ...
    CDFVariables, ...
    'GlobalAttributes', CDFInfo.GlobalAttributes, ...
    'VariableAttributes', CDFInfo.VariableAttributes, ...
    'RecordBound', rbvars, ...	
    'varcompress', varCompress, ...
    'vardatatypes', varDataTypes, ...
    'blockingfactor', blockingFactor, ...
    'padvalues', pad, ...
    'writemode', 'overwrite');

%Check to see if the file was written.  Does not check to see if the file
%was correctly written, only that it exists.  The spdfcdfwrite function
%does not return any kind of information as to whether or not the command
%was a success.
fullFilenameCDF = [fullFilenameCDF, '.cdf'];

if isfile(fullFilenameCDF)
     % File exists.
     exportSuccessFlag = 1;
else
     % File does not exist.
     exportSuccessFlag = 0;
end  %End of if-else clause - if isfile(fullFilenameCDF)

end  %End of the function generateSEEDCDF.m